version: '3'
services:
  ms-ds-ssev:
    container_name: ms-ds-ssev
    restart: always
    build:
      context: .
      args:
        options: --reload
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"