name: ssev_dash
channels:
  - conda-forge
  - defaults
dependencies:
- Cython==0.29.32
- dash==2.7.0
- dash-core-components==2.0.0
- dash-html-components==2.0.0
- dash-renderer==1.9.1
- plotly==5.11.0
- pandas==1.5.2
- gunicorn==20.1.0
- PyYAML==6.0
- gevent==22.10.2
- numpy==1.22.4
- geopandas==0.10.2
- pyproj==3.3.0
- shapely==1.8.2
- cdsapi==0.5.1
- rioxarray==0.11.1
- xarray==0.20.1
- cftime==1.5.1.1
- matplotlib==3.6.2
- cfgrib==0.9.10.1
- pip==22.2.1
- nbformat==5.7.0
- pip:
  - pymongo[gssapi,aws,ocsp,snappy,srv,zstd,encryption]==4.2.0
